import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Time = {
  datetime: string
}

async function getTime():Promise<Time> {
  const res = await fetch(
    'http://worldtimeapi.org/api/timezone/America/Chicago',
    {
      next: {
        revalidate:5,
      }
    }
  );

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const [time] = await Promise.all([getTime()]);

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
